# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check and test the source code
on:
 pull_request:
  branches:
   - main
jobs:
 test:
  name: Check the source code
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.7.7'
   - name: Install dependencies
     run: flutter pub get
     working-directory: ./
   - name: Analyze project source
     run: flutter analyze
     working-directory: ./
   - name: Run tests
     run: flutter test
     working-directory: ./
